version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: pg-test-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/testdb'
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pgdata:
